// start of FETCH POKEDEX
export const FETCH_POKEDEX_START = 'FETCH_POKEDEX_START'
export const FETCH_POKEDEX_SUCCESS = 'FETCH_POKEDEX_SUCCESS'
export const FETCH_POKEDEX_FAIL = 'FETCH_POKEDEX_FAIL'
// end of FETCH POKEDEX

// start of SEARCH TERM
export const SEARCH_TERM_WAS_CHANGED = 'SEARCH_TERM_WAS_CHANGED'
// end of SEARCH TERM

// start of RESET PERSISTED STATE
export const PERSISTED_STATE_WAS_RESET = 'PERSISTED_STATE_WAS_RESET'
// end of RESET PERSISTED STATE

// start of SORT OPTION
export const SORT_OPTION_WAS_CHANGED = 'SORT_OPTION_WAS_CHANGED'
// end of SORT OPTION

// start of EDIT FORM
export const EDIT_FORM_WAS_CHANGED = 'EDIT_FORM_WAS_CHANGED'
export const SUBMIT_BUTTON_FOR_EDIT_WAS_CHANGED = 'SUBMIT_BUTTON_FOR_EDIT_WAS_CHANGED'
// end of EDIT FORM

// start of EDIT POKEMON
export const EDIT_POKEMON_START = 'EDIT_POKEMON_START'
export const EDIT_POKEMON_SUCCESS = 'EDIT_POKEMON_SUCCESS'
export const EDIT_POKEMON_FAIL = 'EDIT_POKEMON_FAIL'
// end of EDIT POKEMON

// start of ADD POKEMON
export const ADD_POKEMON_START = 'ADD_POKEMON_START'
export const ADD_POKEMON_SUCCESS = 'ADD_POKEMON_SUCCESS'
export const ADD_POKEMON_FAIL = 'ADD_POKEMON_FAIL'
// end of ADD POKEMON
