// start of FETCH POKEDEX
export const FETCH_POKEDEX_START = 'FETCH_POKEDEX_START'
export const FETCH_POKEDEX_SUCCESS = 'FETCH_POKEDEX_SUCCESS'
export const FETCH_POKEDEX_FAIL = 'FETCH_POKEDEX_FAIL'
// end of FETCH POKEDEX
