// start of FETCH POKEDEX
export const FETCH_POKEDEX_START = 'FETCH_POKEDEX_START'
export const FETCH_POKEDEX_SUCCESS = 'FETCH_POKEDEX_SUCCESS'
export const FETCH_POKEDEX_FAIL = 'FETCH_POKEDEX_FAIL'
// end of FETCH POKEDEX

// start of SEARCH TERM
export const SEARCH_TERM_WAS_CHANGED = 'SEARCH_TERM_WAS_CHANGED'
// end of SEARCH TERM

// start of RESET PERSISTED STATE
export const PERSISTED_STATE_WAS_RESET = 'PERSISTED_STATE_WAS_RESET'
// end of RESET PERSISTED STATE

// start of SORT OPTION
export const SORT_OPTION_WAS_CHANGED = 'SORT_OPTION_WAS_CHANGED'
// end of SORT OPTION
